
-- Adding Top 100 Software Companies
insert into "company" (name)
values
       ('Google'),
       ('Facebook'),
       ('Netflix'),
       ('Amazon'),
       ('Microsoft'),
       ('Adobe'),
       ('Dropbox'),
       ('IFS'),
       ('Guidewire'),
       ('Cornerstone'),
       ('Secureworks'),
       ('Vertafore'),
       ('Procore'),
       ('Asana'),
       ('iCIMS'),
       ('Autodesk'),
       ('Intuit'),
       ('Altimetrik'),
       ('Workday'),
       ('Salesforce'),
       ('The Trade Desk'),
       ('Qualtrics'),
       ('BlackLine'),
       ('Cisco Systems'),
       ('Nintex'),
       ('PowerSchool'),
       ('Twilio'),
       ('Gainsight'),
       ('Zoho'),
       ('Atlassian'),
       ('VMware'),
       ('Shopify'),
       ('Cvent'),
       ('Talend'),
       ('Templafy'),
       ('Cloudflare'),
       ('MURAL'),
       ('Stack Overflow'),
       ('DataRobot'),
       ('Acquia'),
       ('Imply'),
       ('Argo AI'),
       ('Hootsuite'),
       ('Samsara'),
       ('Planview'),
       ('airSlate'),
       ('Iterable'),
       ('Sisense'),
       ('Pipedrive'),
       ('Pax8'),
       ('Outreach'),
       ('Fivetran'),
       ('Absolute Software'),
       ('Mapbox'),
       ('Code42'),
       ('Sendinblue'),
       ('Alida'),
       ('FiscalNote'),
       ('StellarWP'),
       ('QGenda'),
       ('Articulate'),
       ('Pantheon'),
       ('Namely'),
       ('Conductor'),
       ('Grammarly'),
       ('UserZoom'),
       ('Kibo'),
       ('Panopto'),
       ('Notarize'),
       ('Botkeeper'),
       ('Jungle Scout'),
       ('Lever'),
       ('Influitive'),
       ('Simpplr'),
       ('vcita'),
       ('Visual Lease'),
       ('Widen'),
       ('WhereScape'),
       ('General Global Assistance'),
       ('DealerSocket'),
       ('Domo'),
       ('Genesys'),
       ('Intapp'),
       ('ASAPP'),
       ('Broadridge Financial Services'),
       ('Fastly'),
       ('Ascent'),
       ('Verkada'),
       ('CloudPay'),
       ('FourKites'),
       ('Gofore'),
       ('Identiv'),
       ('Murex'),
       ('mParticle'),
       ('League'),
       ('Protegrity'),
       ('iboss'),
       ('Fireflies.ai'),
       ('Bringg'),
       ('Heap'),
       ('Aclima'),
       ('Drift'),
       ('Beamery');

-- Adding Typical Roles
insert into "role" (name)
values
       ('Front-End Engineer'),
       ('Back-End Engineer'),
       ('Full Stack Engineer'),
       ('Data Scientist'),
       ('Software Engineer in Test (QA Engineer)'),
       ('DevOps Engineer'),
       ('Security Engineer');


insert into "skill" (name)
values
       ('Python'),
       ('Go'),
       ('React'),
       ('HTML'),
       ('CSS'),
       ('JavaScript'),
       ('Java'),
       ('Swift'),
       ('C'),
       ('C++'),
       ('Problem-solving'),
       ('Communication');