version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/ -schemas=postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./backend/flyway/sql:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5432:5432