version: "2.1"
services:
  backend:
    build:
        context: ./backend/api
    ports:
      - 5000:5000
  flyway:
    image: flyway/flyway
    command: -locations=filesystem:/flyway/sql/migration -url=jdbc:postgresql://db:5432/ -schemas=postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./backend/flyway/sql:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5432:5432
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Pacific
      - URL=cjjeon.com
      - SUBDOMAINS=interview-prep-api,
      - VALIDATION=http
      - EMAIL=hello@cjjeon.com
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./prod-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
