-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.


create table company
(
    id         bigint generated by default as identity
        constraint company_pkey
            primary key,
    created_at timestamp with time zone default now(),
    name       varchar not null
);


create table company_description(
	id bigint generated by default as identity
		constraint company_description_pk
			primary key,
	created_at timestamp with time zone default now(),
	description varchar not null,
	company_id bigint not null
	    constraint company_description_company_id_fk
	        references company,
	user_id uuid not null
		constraint company_description_users_id_fk
			references users
);



create policy "Company description can only be created by user."
  on company_description for insert
  with check ( auth.uid() = user_id );

create policy "Company description can only be updated by user."
  on company_description for update
  using ( auth.uid() = user_id );

create policy "Company description are viewable by users who created them."
  on company_description for select
  using ( auth.uid() = user_id );


create or replace function create_company(name text, description text)
returns bigint
language plpgsql
as $$
declare
  new_company_row bigint;
begin
  insert into company(name)
  values (create_company.name)
  returning id into new_company_row;

  insert into company_description(description, company_id, user_id)
  values (create_company.description, new_company_row, auth.uid());

  return new_company_row;
end;
$$;